### ISSUE TITLE
UnhandledPromiseRejectionWarning under Debian

### ISSUE THREAD

**Issue by KristjanESPERANTO** [tuxedocomputers/tuxedo-control-center#130]
I'm trying to get it run under Debian 11 (with a TUXEDO N650DU). I found no pre-build package so I gave the Development setup a shot, but after `npm run start` I can see the GUI only for a second, than I'm getting this output:

```
$ npm run start

> tuxedo-control-center@1.1.0 start
> electron ./dist/tuxedo-control-center

/bin/sh: 1: prime-select: not found
/bin/sh: 1: prime-supported: not found
(node:11288) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/home/kristjan/tuxedo-control-center/tuxedo-control-center/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:206:24)
    at /home/kristjan/tuxedo-control-center/tuxedo-control-center/dist/tuxedo-control-center/e-app/e-app/main.js:150:17
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:11288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tuxedoxt** [comment]
Hello,

you can try to manually download the latest ubuntu deb packages from 

https://deb.tuxedocomputers.com/ubuntu/pool/main/t/

for
- tuxedo-control-center
- tuxedo-keyboard

For the dev setup you might have missed to the copy `com.tuxedocomputers.tccd.conf` step.

**Comment by KristjanESPERANTO** [comment]
I checked, I didn’t forget to copy the `com.tuxedocomputers.tccd.conf` step.

But after installing `tuxedo-control-center` and `tuxedo-keyboard` with the deb files, I can now also start `tuxedo-control-center` with the dev setup. So I added `tuxedo-keyboard` to the dev setup with PR #137.

The ubuntu deb packages work under Debian 11 by the way. Would it make sense to mention the installation under Debian somewhere?

**Comment by tuxedoder** [comment]
I tried to build the 2.1.7 deb package in debian 12 with npm 6.4.18 and node 14.21.3 myself and it worked.

You need some dependencies: `sudo apt install make gcc g++ libudev-dev -y`.

But it currently only seems to work up to python 3.10, [because U file mode was removed in Python 3.11](https://github.com/nodejs/node-gyp/issues/2219). A workaround is update one dependency with `npm explore npm/node_modules/npm-lifecycle -g -- npm install node-gyp@9.0.0` and then install all with `npm i`. Afterwards build with `npm run pack-prod deb`. Keep in mind that you also need to have `tuxedo-drivers`.

To answer the initial question, your error message means that you didn't start the tccd service. Run `sudo ./dist/tuxedo-control-center/data/service/tccd --start` and afterwards `npm run start`. Installing the deb file and rebooting should be enough to set up tccd automatically. 

> Would it make sense to mention the installation under Debian somewhere?

It is mentioned on [our website](https://www.tuxedocomputers.com/en/TUXEDO-Control-Center-and-drivers-under-Debian), but not in the readme. Could be added I think.
