### ISSUE TITLE
Can't find Repository for openSUSE Thumbleweed

### ISSUE THREAD

**Issue by tzabbi** [tuxedocomputers/tuxedo-control-center#153]
Hello all,

can someone tell me the proper repository for openSUSE Thumbleweed? I tried the package from the OpenSUSE Leap 15.2 Repo but after I installed it, my thunderboldport doesn't work anymore so I have to reinstall the OS.

Greetings
Tom

**Comment by alexdesiqueira** [comment]
Hey @tzabbi!
On [your comment](https://github.com/tuxedocomputers/tuxedo-control-center/issues/157#issuecomment-981312780) at #157: I followed the instructions at  _openSUSE_ > _Common packages_ to install TCC for Tumbleweed. Only one fix: instead of using `https://rpm.tuxedocomputers.com/opensuse/15.2/` as the URL, I used `https://rpm.tuxedocomputers.com/opensuse/15.3/`, the latest one. Not sure if there are any differences between 15.2 and 15.3 packages, though.
There isn't a specific Tumbleweed repository (please check https://rpm.tuxedocomputers.com/opensuse/). Also, I ain't use thunderbolt, so I cannot say anything about that.

Just a side note: not sure if TCC would blow up your thunderbolt... maybe a kernel regression did that? I read somewhere that the newest `5.15` is giving headaches to people — when I read it, something was said specifically about bluetooth adapters. Maybe someone more experienced can tell something about that.

**Comment by vinzv** [comment]
Okay, I just checked with an IBS15 and Tumbleweed: Thunderbolt works just fine, even after installing and starting TCC.

This is what I did:
1) Install TW (latest Snapshot 20220207)
2) Added [https://rpm.tuxedocomputers.com/opensuse/15.3/](https://t.co/kGyS02J2bn) via YaST
3) Installed TCC incl. all dependencies
4) Connected a TBT3 Dock

![Screenshot_20220211_140528](https://user-images.githubusercontent.com/74432/153597371-d3114c5a-b127-4c34-92e8-c08f2afd9ab0.png)
![Screenshot_20220211_140619](https://user-images.githubusercontent.com/74432/153597377-b5aa8cc4-29c2-4bf1-af94-bb616c7e7089.png)
