### ISSUE TITLE
Same fan speeds for CPU/GPU 

### ISSUE THREAD

**Issue by weter11** [tuxedocomputers/tuxedo-control-center#245]
Hi! on my system (XMG Apex 17 (Clevo NH77ERQ)) both fans working at the same speed, even when I set GPU speed 0%, it steel working with the same speed as CPU. When fan control disabled both fans work at different speeds according to their temperatures and program show their speeds, so technically it register both fans speeds.
It is a bug or TCC can't control separately fans in Clevo notebooks?
Also after https://github.com/tuxedocomputers/tuxedo-control-center/commit/03dd3035b50c6f5e7709f5156bfa8ffa59d01796 my fans not more work with speeds below 20%, so I delete lines with check for HW capabilities (they are wrong and my fans start spin from 6%): https://github.com/tuxedocomputers/tuxedo-control-center/blob/c1d9d56411c7153bf79d078676639016342623e8/src/service-app/classes/FanControlLogic.ts#L203

**Comment by weter11** [comment]
I found why it uses the same speed and set value to false:
https://github.com/tuxedocomputers/tuxedo-control-center/blob/c1d9d56411c7153bf79d078676639016342623e8/src/service-app/classes/FanControlWorker.ts#L123
Also predefined fan profiles is really bad. ALL modern CPU, GPU work with thermal limits, which controlled on a hardware level. So I set CPU limit to 92°C, GPU limit itself at 87°C (controlled by VBIOS), so now I can play at night with 33% fan speed for GPU, 35% speed for CPU (they have different speed and noise at the same %). GPU uses 70-80W and in some games this is enough.
It would be nice to see in the next release custom fan profiles, it is very hard to find good values for fan speeds using tables and an option to disable same speed for CPU/GPU, CPU sheduler and CPU TDP slider, temperature limit for CPU.

**Comment by enriquezmark36** [comment]
Hello,

Excuse me for butting in. I also already filed a similar issue before (albeit with a more vulgar tone) at https://github.com/tuxedocomputers/tuxedo-control-center/issues/222#issuecomment-1280442490. 

Unfortunately, it was closed. They said it was 'by design'. Both the CPU and the GPU fans are connected (via heatpipes )so that both fans can cool the CPU/GPU. This seems reasonable as the GPU and CPU temps are never that far apart more than 10 degrees centigrade (i.e., the CPU can heat up the GPU and vice versa). 

On the flip side, reading their comment also seems like my idea to speed up the GPU fan first before speeding up the CPU fan is feasible as the GPU fan is significantly less noisy than the CPU fan (in an effort to reduce the noise).

As for solution in the interim, the simplest way is to hack the fan tables (which should be on `src/common/models/TccFanTable.ts`), comment out the `modeSameSpeed` flag, then build from source. 

It would be nice if someone could fork this and at least write a POC on your idea though. It might be additional complexity but it gives more control to the users.

**Comment by weter11** [comment]
To control in a such manner CPU/GPU fan speeds devs need to add special profiles per model or add ability to create custom fan profiles, also yeah shared heat pipes transfer heat from one component to another and according to my tests limit GPU fan on a very low speeds is a bad idea and hugely decrease efficiency even if only CPU have huge load, but it's only about my notebook.
Also as I can see, there some sort of hysteresis to control fans, so app decrease fan speed not immediately, but after some time. And if someone think that app too slow increase fan speeds, I change this lines
https://github.com/tuxedocomputers/tuxedo-control-center/blob/144d0897005b744dc4b52a3f524ce7bde59ccf03/src/service-app/classes/FanControlLogic.ts#L61-L62
to `MAX_SPEED_JUMP = 25` and `SPEED_JUMP_THRESHOLD = 50` and now app increase fan speeds much faster and more close to manufacturer defaults. So with TUXEDO Defaults CPU temperature raise in 6 secs from 49 to 87 °C and fan speed reach 50% in 12secs, my own profile for gaming and huge tasks - temperature went from 42 to 87 °C in 28 seconds, but fan was at 63% after 11 secs, so it slowly increase temperature until reach my predefined values (87 °C and stapm_limit 50W), which was set in RyzenAdj. Previously first it reach temperature limit and only then increase fan speeds.

`PS`: I don't think it's impossible, need to add API for customisation fan speeds.

**Comment by weter11** [comment]
Looks like the latest version partially try to support custom fan curves, but it's buggy (custom curve when active can't register CPU temperature) plus there no ability to set separately fan speed for GPU and CPU and after 76 °C min fan speed 40% and you can't change that, which is really strange. And there no ability to ramp fan speed sharply, only smooth increase, which as I wrote is more irritable than stable fan speed in a big range of temperatures.

**Comment by err0r2k** [comment]
> Looks like the latest version partially try to support custom fan curves, but it's buggy (custom curve when active can't register CPU temperature) plus there no ability to set separately fan speed for GPU and CPU and after 76 °C min fan speed 40% and you can't change that, which is really strange. And there no ability to ramp fan speed sharply, only smooth increase, which as I wrote is more irritable than stable fan speed in a big range of temperatures.

See #355 .You can disable the minimum fan speed at 76°C by editing two files.
Separate fan speed control would be really great!
