### ISSUE TITLE
TCC dashboard uses too much CPU resources

### ISSUE THREAD

**Issue by brunoais** [tuxedocomputers/tuxedo-control-center#26]
Somehow, when I am looking at the dashboard, according to htop, the single threaded CPU usage of TCC is continuously at 100%.

Is this normal? What is the program doing that requires so much CPU power?

**Comment by mschiff** [comment]
I am also seeing high CPU usage. There are two processes.
`node_modules/electron/dist/electron --type=renderer...` is constantly using around 55% CPU
`node_modules/electron/dist/electron --type=gpu-process...` is constantly using around 20% CPU

maybe some screen refresh is occuring way to often or its just because its a node application :-/

**Comment by tuxedoxt** [comment]
I have noticed that the slightly animated version of the gauges increases CPU usage. I have, however, never seen it close to 100% though, that's rather excessive. I'll have a look if something has changed.

**Comment by brunoais** [comment]
I'd rather turn off the animations. It's not worth the resource usage.

**Comment by tuxedoxt** [comment]
In an attempt to find a middle way and reduce dashboard cpu usage, animations has been somewhat... tuned down ;) (as of 1.0.4) please let me know how it works.

**Comment by brunoais** [comment]
@tuxedoxt Seems to be working much better. Looks much lighter now. Thank you.
