### ISSUE TITLE
Backlight does not start automatically on Pulse 14 after each boot

### ISSUE THREAD

**Issue by Nintendo7686** [tuxedocomputers/tuxedo-control-center#300]
On Pulse 14, Manjaro KDE, the keyboard backlight does not start automatically. The laptop will turn on and the backlight will be OFF (even with the last state left at ON). Using Fn+Space returns backlight set to 0% (OFF), which means nothing happens since the backlight was already OFF. I can then Fn+Space again to turn it ON to whatever setting in my TCC settings. The backlight works fine when waking from sleep.

`dkms status` returns the following

```
tuxedo-keyboard/3.2.3, 6.3.3-1-MANJARO, x86_64: installed
v4l2loopback/0.12.7, 6.3.3-1-MANJARO, x86_64: installed
```

TCC is at 2.0.5 (from AUR), tuxedo-keyboard-dkms 3.2.3 (from Manjaro Official repositories - community), and kernel 6.3

The issue was also observed in TCC 2.0.4, and also when I was running kernel 6.2

**Comment by crissi-tuxedo** [comment]
Hey Nintendo,

since your original request alot of updates happened for TCC and tuxedo-drivers, do you still have problems?

best regards, Crissi

**Comment by Nintendo7686** [comment]
Hi Crissi,

It still happens but it is now more of an erratic behaviour, sometimes comes on, sometimes not - which I know is not helpful at all for developers... I will keep a closer look a see if I can associate it with anything in particular. 
Thanks

**Comment by crissi-tuxedo** [comment]
Thanks for your reply! 

I am sorry to hear that you still have issues. I hope it does not bother you too much.

Since tuxedo-drivers is under constant development, I am sure your bugs will be ironed out eventually :)

I will close this issue for now, if you have any news, feel free to reopen (or open an issue in the tuxedo-drivers repo if it's about the keyboard backlight again)

best regards, 
Crissi
