### ISSUE TITLE
Issue with 2.1.2- new fan control features not working

### ISSUE THREAD

**Issue by MARTINrichard05** [tuxedocomputers/tuxedo-control-center#342]
When i set a maximum fan speed it is not respected
when i set a custom curve, the cpu fan speed and temp reading are stuck and i get this in tccd logs :

Failed executing onWork() => TypeError: Cannot read property 'sort' of undefined

i'm on a aura 15 gen 2 on fedora 39

**Comment by TheRealAgentK** [comment]
I can confirm the second part of the issue on Ubuntu Budgie on a IB Pro 14 Gen 7.

With a custom fan curve, CPU temp is visually being stuck to whatever it was in TCC Dashboard when the curve was activated and because of that, fan speed doesn't change accordingly. Tracking these parameters in the Budgie System Monitor widget shows the correct values for temp but TCC doesn't seem to be able to see them.

This is a problem if you activate a custom fan curve and don't realise quickly enough that TCC stopped controlling the fan speed. Might well cause thermal hardware damage if left to its own devices long enough.

**Comment by MARTINrichard05** [comment]
For anyone that wonder
I already opened a ticket and they told me they are working on the issue. They just d'ont know when exactly there will be a fix, but they work on it.

**Comment by MARTINrichard05** [comment]
fixed with 2.1.3, my aura 15 gen 2 doesnt sound like a ps4 running cyberpunk no more

**Comment by MARTINrichard05** [comment]
fixed with 2.1.3, my aura 15 gen 2 doesnt sound like a ps4 running cyberpunk no more
