### ISSUE TITLE
Batttery not Charging after upgrade

### ISSUE THREAD

**Issue by Vitamin-X** [tuxedocomputers/tuxedo-control-center#383]
I installed the new kernel version 6.5.0-28 in my Ubuntu and after that the Battery wont charge at all anymore

When i check with upower it keeps saying the charge rate is 0W, booting the old kernel wont help also, so i believe it caused by the tuxedo control center update that happen at the same time

When i start Windows the Battery charges just fine, but in linux not at all anymore, also when i disconnect the power from the notebook it seems like the percents are just flying by not even 1min for 1%

Also i have never seen the "battery Charging Options" menu inside the TCC software befor, it appeared after the update.
But Changing anything just changes the state inside upower from "charging" to "pending-charge" but the rate stays at 0w

Never had an issue with any battery inside linux so im not exacly sure where to start looking, atleast syslog and dmesg didnt show anything specific 

OS: xUbuntu 23.10
Kernel: 6.5.0-28
Model: Clevo PC70HR
TCC: 2.1.8

**Comment by crissi-tuxedo** [comment]
Hey Vitamin-X,
thanks for your bug report.

Have you tried to immediately reboot after changing battery options?
Someone else wrote that this helped them. 

Also you write your Laptop is a Clevo, sadly we cannot give any official support for them.
Even if it seems like it is hardware identical to one of our models, there can be minute differences that can lead to unexpected behaviour and even to damage to your hardware, so if you use our drivers it is at your own risk.
It is likely that the BIOS Firmware differences or a tiny change in the hardware revision are responsible for your problems.

It is possible that there is a setting in your devices BIOS Setup Menu to change the charging options too, you could check that out and try if it changes anything.

Since this is likely not an issue with TCC I will close your issue, but feel free to re-open or open another one if you have problems related to TCC.

best regards,
Crissi

**Comment by Vitamin-X** [comment]
got it solved, when changing the battery settings inside the TCC software, it messes up the Flexicharge Settings inside my bios, when i click any option inside TCC my whole notebook freezes for a couple of seconds and it wont charge at all then

to solve it, i needed to enter the bios and disable and enable flexicharge again, i also tried changing the values, after a couple of tries it just started working again and then i havent touched the settings anymore

now i mostly wonder, why it was working inside windows, maybe it overwrites the settings or something.
