### ISSUE TITLE
Tuxedo Control Center another case of no temperatures or fan

### ISSUE THREAD

**Issue by kchaliki** [tuxedocomputers/tuxedo-control-center#415]
Hello there, a couple of days ago the fans went nuts out of the blue and the computer behaved like it was under a lot of load when in fact I had closed most apps. After turning off and on again, the fan has basically stopped running and there are no temp or fan speed readings in the control panel any more. It used to always run for a few seconds on boot or wake up from suspend at full speed but that's not happening any more.

I tried following along what was said [here](https://github.com/tuxedocomputers/tuxedo-control-center/issues/387) but I can't find tuxedo_io, so then I tried to build the tuxedo-driver deb packager per the instructions [here](https://github.com/tuxedocomputers/tuxedo-drivers) so I could install it but I am stuck at this error:   
```
$ make package-deb 
debuild --no-sign
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: source package tuxedo-drivers
dpkg-buildpackage: info: source version 4.10.0
dpkg-buildpackage: info: source distribution jammy
dpkg-buildpackage: info: source changed by Werner Sembach <tux@tuxedocomputers.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: dh-sequence-dkms
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
make: *** [Makefile:69: package-deb] Error 29
```
I tried to apt install dh-dkms or dh-sequence-dkms but I'm getting `unable to locate package`. I am kind of worried the fan won't work when it should!

Any ideas?

**Comment by tuxedoder** [comment]
It sounds like `tuxedo-drivers` was not installed correctly and not a control center bug. Temperature and fan speed is missing in the dashboard if `tuxedo-drivers` is not available. You can check if the dkms is available with `sudo dkms status`, it should match your current kernel `uname -r`. 

Example:
```
uname -r
6.11.0-103009-tuxedo

sudo dkms status
tuxedo-drivers/4.8.0, 6.11.0-102007-tuxedo, x86_64: installed
tuxedo-drivers/4.8.0, 6.11.0-103009-tuxedo, x86_64: installed
```
You can try to reinstall everything with `sudo apt purge tuxedo-control-center tuxedo-drivers && sudo apt install tuxedo-control-center -y`.

Which device is it?

**Comment by kchaliki** [comment]
It's the infinitybook pro gen6. I indeed do not see `tuxedo-drivers` when I run `dkms status`
```
$ dkms status
tuxedo-keyboard, 3.1.4, 5.15.0-10122-tuxedo, x86_64: installed
tuxedo-keyboard, 3.1.4, 5.15.0-10124-tuxedo, x86_64: installed (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!) (WARNING! Diff between built and installed module!)
tuxedo-micfix1, 1.2.37: added
virtualbox, 6.1.48, 5.15.0-10122-tuxedo, x86_64: installed
virtualbox, 6.1.48, 5.15.0-10124-tuxedo, x86_64: installed
```
I ran the command to reinstall everything and also restarted the computer again but no luck, still same behaviour in the control panel and same output from `dkms status`. I also noticed this in the output `Package 'tuxedo-drivers' is not installed, so not removed`

**Comment by tuxedoder** [comment]
Try to update your system with `sudo apt update -y && sudo apt upgrade -y` and reboot. Backup important files prior to doing so, because I am not sure if such a big version change will flawlessly work. It shows 5.15 in the dkms log, but the current kernel version is 6.11. I am not sure what kernel you use, since you didn't show the `uname -r` output, but it seems like the system didn't get updates since a long time. 

If it doesn't work after updating and `uname -r` shows 6.11, purge `tuxedo-control-center`, `tuxedo-keyboard` and `tuxedo-drivers`, and install it again with `sudo apt install tuxedo-control-center -y`.

Reinstalling the operating system could be an alternative to make sure that everything is configured and up-to-date.

For further questions it would be better to contact [support](https://www.tuxedocomputers.com/en/Contact.tuxedo). Closing this issue since this is not a tcc bug.
