### ISSUE TITLE
system crash on modprobe tuxedo_tuxi_fan_control > /dev/null 2>&1 || true

### ISSUE THREAD

**Issue by FaKod** [tuxedocomputers/tuxedo-control-center#421]
My system reboots while executing `modprobe tuxedo_tuxi_fan_control > /dev/null 2>&1 || true` in script `/var/lib/dpkg/info/tuxedo-drivers.postinst`

Kernel: 6.9.3-76060903-generic
tuxedo-drivers version 4.11.2

I worked around with commenting out the modprobe statement

**Comment by dekoration** [comment]
I have the same problem. 
Update hangs on modprobe tuxedo_tuxi_fan_control > /dev/null 2>&1 || true

commented out the line, update went without problems

**Comment by tuxedoder** [comment]
This sounds like a `tuxedo-drivers` bug. I think you mean [this](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers/-/issues/222). Closing issue because driver related issues should be mentioned in [`tuxedo-drivers`](https://gitlab.com/tuxedocomputers/development/packages/tuxedo-drivers) instead.

**Comment by FaKod** [comment]
Fiine. I saw this https://github.com/tuxedocomputers/tuxedo-drivers but there is no issues.
Did not know, that there is a Gitlab account too. 
However, I would have preferred this to be fixed. A reboot is serious, I'm just saying.
