### ISSUE TITLE
Fan control no longer working after updating tccd from 2.1.13 for Sirius 16 gen 1

### ISSUE THREAD

**Issue by Szybet** [tuxedocomputers/tuxedo-control-center#425]
As in the title, the exact commit it was working on was `2fca7138a29e25d1496156f50426691001334404`, recently I updated everything tuxedo and it stopped working. After i replaced the new tccd with the old one, it started to work again. 

Also, maybe consider this: https://www.reddit.com/r/tuxedocomputers/comments/1gvzabo/feedback_on_the_sirius_16_fan_control_and/

**Comment by tuxedoder** [comment]
> the exact commit it was working on was 2fca7138a29e25d1496156f50426691001334404, recently I updated everything tuxedo and it stopped working

This commit looks like 2.1.13 [and `tccd` tries to use a hwmon interface which results in high cpu usage on a Sirius, because old versions do not know the new hwmon path](https://github.com/tuxedocomputers/tuxedo-control-center/issues/37#issuecomment-2498227118). 2.1.14 uses a new `tuxi` hwmon interface on a Sirius without fallback to the other one. [Try to apply updates.](https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Updating-EFI-BIOS-EC.tuxedo)

> Also, maybe consider this: https://www.reddit.com/r/tuxedocomputers/comments/1gvzabo/feedback_on_the_sirius_16_fan_control_and/

The current code makes an average to filter out extreme values. 

https://github.com/tuxedocomputers/tuxedo-control-center/blob/c2d4a9b6231d84f564ac72c457ba991ada52fdde/src/service-app/classes/FanControlLogic.ts#L39-L55

> the worker in tccd has a delay of 1s. I changed it to 150 ms

> it increased the already high cpu usage of the service, but that's the problem it's written in node. 

[By increasing the amount of how often the worker is active the amount of EC communication increases as well and has not much to do with node.](https://github.com/tuxedocomputers/tuxedo-control-center/issues/37#issuecomment-2163182242) With increased speed the calculated average adjusts faster which was seen.

**Comment by Szybet** [comment]
I have the latest bios & EC, the tuxi driver seems to be installed and initialised (because I updated everything)
```
sirius :: ~ » sudo dmesg | grep tuxi
[sudo] password for szybet: 
[    8.230058] tuxi_acpi: interface initialized
sirius :: ~ » lsmod | grep tuxi
tuxedo_tuxi_fan_control    20480  0
tuxi_acpi              20480  1 tuxedo_tuxi_fan_control
sirius :: ~ » 
```
So what should I check? Why doesn't it work?

> With increased speed the calculated average adjusts faster which was seen

That's the point, 1s is too long for such a powerful cpu & gpu... What am I even talking about, have you tried a few times to make the cpu and gpu for 100% when the fans were fully turned off? Did it crash, freeze?

**Comment by tuxedoder** [comment]
> So what should I check?

The code does look in hwmon. There can be up to two `name` paths `/sys/class/hwmon/` for fans. `name` can be `tuxedo` which would be the initial one and/or `tuxedo_tuxi_sensors` if it is `tuxi`. The `tuxi` path must exist or the fan control won't work in `tcc`.

The code does this by doing `grep -rl '^tuxedo_tuxi_sensors$' /sys/class/hwmon/*/name | sed 's|/name$||'`.


> That's the point, 1s is too long for such a powerful cpu & gpu
> make the cpu and gpu for 100% when the fans were fully turned off

By using fans normally nothing happened, but please **never try to have 0% fan speed for a long time with high utilization**. `tcc` won't even allow this.

https://github.com/tuxedocomputers/tuxedo-control-center/blob/094e07c294afbb760da1bcb490b6c585f75e8401/src/common/classes/FanUtils.ts#L65-L70

I mentioned it as feedback internally. If you want to be on the safer side, you can increase the worker speed. With `tuxi` the cpu load shouldn't be very high.

**Comment by Szybet** [comment]
The issue was that I updated everything to use the tuxi interface while the bios update enabling it wasn't yet out, a small window when it was broken - obviously flashing the bios fixed it.

> By using fans normally nothing happened

I'm not talking about the default settings but the setting I was allowed to set in tuxedo control center

> never try to have 0% fan speed for a long time with high utilization. tcc won't even allow this

When there is cpu usage, there is temperature so the fans spin up too, the problem are spikes

Yea, the manageCriticalTemperature is probably called only once a second

> I mentioned it as feedback internally. If you want to be on the safer side, you can increase the worker speed. With tuxi the cpu load shouldn't be very high.

Thanks, yes I will
