### ISSUE TITLE
CPU & GPU Fans showing 0%

### ISSUE THREAD

**Issue by davidrhoderick** [tuxedocomputers/tuxedo-control-center#49]
I've been trying to control my GPU fan on my System 76 Oryx Pro 4 (which should be similar to a Clevo P955ER) for about a month now.  I am able to use the Control Center in Windows from Clevo to control the fan profile and upon restart into Pop!_OS, I'm able to see a drop in fan speed but after rebooting a second time, it appears the fans are back up to ~5000RPM with minimal usage and heating of the GPU (GPU temperature is around 50°C +/- 10°C, which comes from the Vitals GNOME extension).

I've tried the `nvidia-settings` app, GreenWithEnvy, and now the Tuxedo Control Center apps and haven't been able to control the fans yet:

- In `nvidia-settings`, even with `coolbits` set to `28` (or `255`) I don't have controls over the fan.  I believe there should be a slider but it doesn't show up.
- GreenWithEnvy I can offset the GPU clocks by -200MHz and -1000MHz, which has helped a little bit minimize the ridiculous overpowering of the GPU when just running Firefox, Slack, and using an external monitor.  However, the fan duty and RPM are blank so there doesn't appear to be access to the fan from GWE.
- In Tuxedo Control Center, I can set up a profile and it says it's applied but the RPM are still reading near 5000RPM, which doesn't match the "Silent" fan setting to me.  Plus, Tuxedo Control Center shows both CPU and GPU fans at 0%.

Are there any debugging steps I can take to figure out how to add CPU and GPU fan control to Tuxedo Control Center?  Should I remove these other programs (I'm hesitant to remove GWE since it is underclocking the GPU "successfully" so far)?  Where I can I look to provide logs?

**Comment by tuxedoxt** [comment]
If standard clevo it would probably work since the interfaces are pretty general.

As far as I am aware System 76 is either sometimes or always supplying non-clevo firmware with their devices (coreboot and possibly ec). If this is the case and since TCC is displaying fan values, it thinks it is in control without changing anything. This situation you describe could for example occur with an incomplete (or different) implementation of the clevo acpi (wmi) interface.

You can still use TCC to limit the CPU clock to prevent some heat generation. However if the clevo interface is not there, it either has the be implemented in the acpi so that TCC works as it is or you need to implement the possibly alternative interface present into your version of TCC/tuxedo-cc-wmi.

Closing this for now as appearing not to be a direct issue with TCC. Feel free to reopen if it should.

**Comment by davidrhoderick** [comment]
@tuxedoxt that could be true; however, according to [this article](https://support.system76.com/articles/transition-firmware/) and the output below, I'm on a proprietary firmware version:

    cat /sys/class/dmi/id/bios_version
    1.07.11RSA4-1

At least it's not 100% System76 open firmware, might they be still be affected by S76 code?  What's the latest version that it should be and might that be holding it back?

**Comment by jmakov** [comment]
Same issue here on an old i7 Clevo laptop. The `sensors` command shows CPU temps, Control Center 0°C.
