### ISSUE TITLE
CPU Frequency not showing, unable to change profile

### ISSUE THREAD

**Issue by bwyyoung** [tuxedocomputers/tuxedo-control-center#58]
I currently am using a laptop named Forge 15R by Aftershock (Equivalent to TUXEDO Book XA15)
https://www.tuxedocomputers.com/en/Linux-Hardware/Linux-Notebooks/15-16-inch/TUXEDO-Book-XA15-Gen10.tuxedo

The laptop is running the latest Pop! OS: Linux pop-os 5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu SMP Wed Nov 11 22:42:16 UTC  x86_64 x86_64 x86_64 GNU/Linux

BIOS version is Insyde Corp 1.07.07, dated 3/6/2020

I am trying to install Tuxedo Control Center on this laptop. I installed it using the PPA package. As I run it, I am unable to change profiles to something other than default, and the current CPU frequency is not visible:
![Screenshot from 2020-11-19 09-04-40](https://user-images.githubusercontent.com/1365439/99607712-4bf00d80-2a47-11eb-8279-e9c15bab02ad.png)

Can someone help me, even though I know that TCC may not be compatible with my laptop / OS?

**Comment by tuxedoxt** [comment]
Hello,

this is a known issue with the model + cpu combination and is being investigated. Would you mind sharing which CPU you are using?

**Comment by bwyyoung** [comment]
I am using AMD 3950X

**Comment by bwyyoung** [comment]
Hi Tuxedo. Is there any update?

**Comment by Matombo** [comment]
Hi,
yes: We found a working fix, but it is not yet packed in an easily install able way.

Some technical insight (**Not** a Tutorial): The cause is a wrongly configured ACPI table, causing ACPI errors seen in the kernel log during boot. This is also causing the cpufreq kernel module to fail on cores 25-32 which is used as the backend by the Tuxedo Controll Center for everything CPU frequency related.

We extracted the ACPI tables using acpidump and disassembled them using iasl. We found the root of the ACPI errors in ssdt2 and ssdt6: ssdt2 has a list of CPU cores which ends with core 24 (C017 <- hex starting with index 0) while ssdt6 correctly counts up to core 32 (C01F). We fixed ssdt2 and recompiled it with iasl. We then temporary overloaded the built in one with the new one with Grubs "acpi" command.

We are currently evaluating the options to pack the fix in a more permanent solution, which will be soon available as an update for TUXEDO XA15 Laptops.

**Comment by Matombo** [comment]
Our fix is ready, if you are on TUXEDO_OS or are using tuxedo-tomte the fix schould arrive automatically.

Currently there is a check for latest UEFI version, but that will be removed soon.

For everyone else there is this repo: https://github.com/tuxedocomputers/tuxedo-corefix-clevo-nh5xax

It adds the fix to the initramfs image to load it during early boot. For this initramfs-tools und dracut are supported and tested on Ubuntu and OpenSUSE respectively. It should work on Pop! OS too.

The Arch distro family sadly uses yet another initramfs build method, but it should be easily adoptable by someone who is willing to maintain a pkgbuild.

**Comment by bwyyoung** [comment]
Thank you. It works. I am very grateful. POP OS now has proper CPU and fan controls. It works on my NH5xAx.

**Comment by bwyyoung** [comment]
Only problem is that the CPU gauge on TCC now shows a fixed 2.2GHz. It does not fluctuate. 

This is different from the value reflected from a tool like CoreCtrl

![Screenshot from 2021-02-06 23-48-28](https://user-images.githubusercontent.com/1365439/107123022-38ca3c80-68d6-11eb-9ea6-de23d5a11b1b.png)

**Comment by Matombo** [comment]
tcc averages the temperature of all cores.

Can you check if this is causing the discrepancy?

If you apply load to all cores, what is displayed then?
