### ISSUE TITLE
Webcam not supported on Pulse 15?

### ISSUE THREAD

**Issue by lmoellendorf** [tuxedocomputers/tuxedo-control-center#64]
I just installed 

- tuxedo-keyboard v3.0.1
- tuxedo-cc-wmi v0.1.7
- tuxedo-control-center v1.0.8

tccd is up and running

And these kernel modules are loaded:

- tuxedo_keyboard
- clevo_acpi
- tuxedo_io
- clevo_wmi
- uvcvideo

If I open tuxedo control center dashboard the webcam is greyed out and a pop appears: "This feature is not supported on your model."

Do I miss something?

**Comment by tuxedoxt** [comment]
Hello,

let me try to clarify. The feature in question is hardware disconnect of webcam for which we currently do not have the control for Pulse. Therefore it is correctly displaying that it is not supported on your model. Due to interest we might implement another software disconnect for devices not supporting this.

Btw the modules loaded will be slightly different once you restart after installation since the kernel will only load the necessary ones.
