### ISSUE TITLE
Dashboard - webcam always active

### ISSUE THREAD

**Issue by unsetglobbing** [tuxedocomputers/tuxedo-control-center#94]
Insanitybook
Ubuntu 18.04.5 LTS
Tuxedo Control Center 1.0.11

Dashboard reports webcam as active even when webcam is deactivated.

**Comment by tuxedoxt** [comment]
Hello,

like in #93 the profile setting is displayed and set upon profile activation, not the current value.

If it is not set correctly upon profile activation (i.e not changed manually by for example Fn key combo) it would be a bug, otherwise it's working as intended.

For transparency maybe it would be useful to display the current state as well. I'll make a note.
